/**
 * Genesis Processing Types
 *
 * Type definitions for the silent genesis processing pipeline,
 * including clustering, completeness detection, and event handling.
 *
 * @module zo/genesis/types
 */

/**
 * Result of semantic clustering for a set of thoughts.
 */
export interface ClusteringResult {
  /** Clusters generated by the algorithm */
  clusters: ClusterCandidate[];

  /** Thoughts that couldn't be grouped (outliers) */
  outliers: string[];

  /** Time taken for clustering (ms) */
  processingTimeMs: number;

  /** Whether LLM pass was required */
  usedLlmPass: boolean;
}

/**
 * A cluster candidate before confirmation.
 */
export interface ClusterCandidate {
  /** Temporary ID for the cluster */
  id: string;

  /** Thought IDs in this cluster */
  thoughtIds: string[];

  /** Centroid embedding vector */
  centroid: number[];

  /** Average similarity within cluster */
  coherenceScore: number;

  /** LLM-generated theme (if LLM pass ran) */
  theme?: string;

  /** LLM-generated name (if LLM pass ran) */
  suggestedName?: string;
}

/**
 * Configuration for the hybrid clustering algorithm.
 */
export interface ClusteringConfig {
  /** Minimum similarity for fast pass grouping (0.0-1.0) */
  similarityThreshold: number;

  /** Maximum thoughts per cluster before splitting */
  maxClusterSize: number;

  /** Minimum thoughts to form a cluster */
  minClusterSize: number;

  /** Similarity variance threshold to trigger LLM pass */
  ambiguityThreshold: number;
}

/**
 * Completeness assessment for a genesis session.
 */
export interface CompletenessAssessment {
  /** Overall completeness score (0.0-1.0) */
  score: number;

  /** Individual heuristic scores */
  heuristics: {
    coverage: number;
    depth: number;
    closureLanguage: number;
    repetitionPlateau: number;
    explicitScope: number;
  };

  /** Whether the session is complete enough to offer reveal */
  readyForReveal: boolean;

  /** Human-readable summary */
  summary: string;
}

/**
 * Events emitted during genesis processing.
 */
export type GenesisEvent =
  | { type: "thought_added"; thoughtId: string }
  | { type: "clustering_started" }
  | { type: "clustering_completed"; result: ClusteringResult }
  | { type: "completeness_updated"; assessment: CompletenessAssessment }
  | { type: "ready_for_reveal" };

/**
 * Callback for genesis processing events.
 */
export type GenesisEventHandler = (event: GenesisEvent) => void;
